services:
  certd:
    image: greper/certd:1.38.7
    restart: unless-stopped
    networks:
      - acepanel-network
    volumes:
      - ./data/certd:/app/data
    ports:
      - ${CERTD_PORT_HTTP}:7001
      - ${CERTD_PORT_HTTPS}:7002
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:7001 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  acepanel-network:
    external: true
