services:
  koishi:
    image: koishijs/koishi:v1.15.0
    restart: unless-stopped
    environment:
      - TZ=${KOISHI_TIME_ZONE}
    networks:
      - acepanel-network
    ports:
      - ${KOISHI_PORT_HTTP}:5140
    volumes:
      - ./data:/koishi
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:5140 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  acepanel-network:
    external: true
