services:
  percona:
    image: percona:8.4
    restart: unless-stopped
    environment:
      - INIT_ROCKSDB=1
      - PERCONA_TELEMETRY_DISABLE=1
      - MYSQL_ROOT_PASSWORD=${PERCONA_ROOT_PASSWORD}
    ports:
      - ${PERCONA_PORT}:3306
    volumes:
      - ./data/:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./log:/var/log/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${PERCONA_ROOT_PASSWORD}" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    networks:
      - acepanel-network

networks:
  acepanel-network:
    external: true
