services:
  lskypro:
    image: halcyonazure/lsky-pro-docker:latest
    restart: unless-stopped
    networks:
      - acepanel-network
    volumes:
      - ./data:/var/www/html/
    ports:
      - "${LSKY_PRO_PORT_HTTP}:8089"
    environment:
      - "WEB_PORT=8089"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:8089 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  acepanel-network:
    external: true
