services:
  lskypro:
    image: halcyonazure/lsky-pro-docker:latest
    restart: unless-stopped
    networks:
      - acepanel-network
    volumes:
      - ./data:/var/www/html/
    ports:
      - "${LSKY_PRO_PORT_HTTP}:8089"
    environment:
      - "WEB_PORT=8089"

networks:
  acepanel-network:
    external: true
