services:
  gatus:
    image: twinproduction/gatus:v5.35.0
    ports:
      - ${GATUS_PORT_HTTP}:8080
    volumes:
      - ./config:/config
      - ./data:/data/
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - acepanel-network
networks:
  acepanel-network:
    external: true
