services:
  qinglong:
    image: whyour/qinglong:2.20.1
    networks:
      - acepanel-network
    volumes:
      - ./data:/ql/data
    ports:
      - "${QINGLONG_PORT_HTTP}:5700"
    restart: unless-stopped
networks:
  acepanel-network:
    external: true
