services:
  bitwarden:
    restart: always
    networks:
      - acepanel-network
    ports:
      - "${VAULTWARDEN_PORT_HTTP}:80"
    volumes:
      - ./data:/data
    image: vaultwarden/server:1.35.2-alpine
networks:  
  acepanel-network:  
    external: true
