services:
  bitwarden:
    image: vaultwarden/server:1.35.2-alpine
    restart: unless-stopped
    networks:
      - acepanel-network
    ports:
      - "${VAULTWARDEN_PORT_HTTP}:80"
    volumes:
      - ./data:/data
networks:  
  acepanel-network:  
    external: true
