services:
  grafana:
    image: grafana/grafana:12.3.1
    restart: unless-stopped
    user: '0'
    networks:
      - acepanel-network
    ports:
      - "${GRAFANA_PORT_HTTP}:3000"
    volumes:
      - ./data:/var/lib/grafana

networks:
  acepanel-network:
    external: true
