services:
  homeassistant:
    image: homeassistant/home-assistant:2026.1.3
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./data:/config"
      - "/run/dbus:/run/dbus:ro"
    environment:
      - TZ=${HOME_ASSISTANT_TIME_ZONE}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:8123 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
