services:
  gitlab:
    image: gitlab/gitlab-ce:18.8.2-ce.0
    networks:
      - acepanel-network
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - "${GITLAB_PORT_HTTP}:80"
      - "${GITLAB_PORT_SSH}:22"
    environment:
      TZ: ${GITLAB_TIME_ZONE}
    volumes:
      - "./data/config:/etc/gitlab"
      - "./data/logs:/var/log/gitlab"
      - "./data/data:/var/opt/gitlab"
    shm_size: ${GITLAB_SHM_SIZE}
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:80/-/health || exit 1" ]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 300s
networks:
  acepanel-network:
    external: true
