services:
  act_runner:
    image: gitea/act_runner:0.2.13
    restart: unless-stopped
    networks:
      - acepanel-network
    volumes:
      #- ./data/config.yaml:/config.yaml # 可选配置
      - ./data/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #- CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=${GITEA_INSTANCE_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${RUNNER_REGISTRATION_TOKEN}
      - GITEA_RUNNER_NAME=${RUNNER_NAME}
      - GITEA_RUNNER_LABELS=${RUNNER_LABELS}
networks:
  acepanel-network:
    external: true