services:
  elasticsearch:
    restart: always
    networks:
      - acepanel-network
    ports:
      - "${ELASTICSEARCH_PORT_HTTP}:9200"
    volumes:
      - "./data/data:/usr/share/elasticsearch/data"
      - "./data/backup:/usr/share/elasticsearch/backup"
      - "./data/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    image: elasticsearch:9.2.4
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=${ELASTICSEARCH_SECURITY}
      - ${ELASTICSEARCH_JAVA_OPTS}

networks:
  acepanel-network:
    external: true
