networks:
  acepanel-network:
    external: true
services:
  certimate:
    image: certimate/certimate:v0.4.14
    networks:
      - acepanel-network
    ports:
      - ${CERTIMATE_PORT_HTTP}:8090
    environment:
      - http_proxy=${CERTIMATE_HTTP_PROXY}
      - https_proxy=${CERTIMATE_HTTPS_PROXY}
      - NO_PROXY=${CERTIMATE_NO_PROXY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/pb_data
    restart: unless-stopped
