services:
  certimate:
    image: certimate/certimate:v0.4.15
    networks:
      - acepanel-network
    ports:
      - ${CERTIMATE_PORT_HTTP}:8090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/pb_data
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:8090 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
networks:
  acepanel-network:
    external: true
