services:
  rustdesk-server:
    image: rustdesk/rustdesk-server-s6:1.1.15
    restart: unless-stopped
    networks:
      - acepanel-network
    ports:
      - "${RUSTDESK_PORT_NAT}:21115"
      - "${RUSTDESK_PORT_HBBS}:21116"
      - "${RUSTDESK_PORT_HBBS}:21116/udp"
      - "${RUSTDESK_PORT_HBBR}:21117"
      - "${RUSTDESK_PORT_WEB_CLIENT_1}:21118"
      - "${RUSTDESK_PORT_WEB_CLIENT_2}:21119"
    volumes:
      - "./data/hbbs:/data"
    environment:
      - "RELAY=${HOST_ADDRESS}:${RUSTDESK_PORT_HBBR}"
      - "ENCRYPTED_ONLY=1"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 21116 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  acepanel-network:
    external: true
