services:
  nginx:
    image: nginx:1.29.5-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_HTTP}:80
      - ${NGINX_PORT_HTTPS}:443
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - acepanel-network
networks:
  acepanel-network:
    external: true
