services:
  adguardhome:
    image: adguard/adguardhome:v0.107.71
    restart: unless-stopped
    networks:
      - acepanel-network
    ports:
      - ${ADGUARDHOME_PORT_DNS}:53/tcp
      - ${ADGUARDHOME_PORT_DNS}:53/udp
      - ${ADGUARDHOME_PORT_DHCP_1}:67/udp
      - ${ADGUARDHOME_PORT_DHCP_2}:68/udp
      - ${ADGUARDHOME_PORT_HTTP_1}:80/tcp
      - ${ADGUARDHOME_PORT_DOH}:443/tcp
      - ${ADGUARDHOME_PORT_DOH}:443/udp
      - ${ADGUARDHOME_PORT_HTTP}:3000/tcp
      - ${ADGUARDHOME_PORT_DOT}:853/tcp
      - ${ADGUARDHOME_PORT_QUIC_1}:784/udp
      - ${ADGUARDHOME_PORT_DOT}:853/udp
      - ${ADGUARDHOME_PORT_QUIC_2}:8853/udp
      - ${ADGUARDHOME_PORT_DNS_CRYPT}:5443/tcp
      - ${ADGUARDHOME_PORT_DNS_CRYPT}:5443/udp
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3000 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  acepanel-network:
    external: true
