services:
  one-api:
    image: justsong/one-api:v0.6.10
    restart: unless-stopped
    ports:
      - ${ONE_API_PORT_HTTP}:3000
    networks:
      - acepanel-network
    volumes:
      - ./data:/data
    environment:
      - SQL_DSN=${ONE_API_DB_USER}:${ONE_API_DB_USER_PASSWORD}@tcp(${ONE_API_DB_HOST}:${ONE_API_DB_PORT})/${ONE_API_DB_NAME}
      - TZ=${ONE_API_TIME_ZONE}
networks:
  acepanel-network:
    external: true
