services:
  ollama:
    image: ollama/ollama:0.15.1
    restart: unless-stopped
    ports:
      - ${OLLAMA_PORT_HTTP}:11434
    networks:
      - acepanel-network
    tty: true
    volumes:
      - ./data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:11434 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  acepanel-network:
    external: true