services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.1.0-beta.3
    restart: unless-stopped
    networks:
      - acepanel-network
    volumes:
      - ./data:/app/data
    ports:
      - ${UPTIME_KUMA_PORT_HTTP}:3001
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:3001 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  acepanel-network:
    external: true