services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.1.0-beta.3
    restart: unless-stopped
    networks:
      - acepanel-network
    volumes:
      - ./data:/app/data
    ports:
      - ${UPTIME_KUMA_PORT_HTTP}:3001
networks:
  acepanel-network:
    external: true