services:
  pgadmin4:
    image: dpage/pgadmin4:9.12
    restart: unless-stopped
    user: "0:0"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      UMASK: 022
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./data:/var/lib/pgadmin
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:80/misc/ping || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - acepanel-network
networks:
  acepanel-network:
    external: true