services:
  pgadmin4:
    image: dpage/pgadmin4:9.11
    restart: unless-stopped
    user: "0:0"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      UMASK: 022
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./data:/var/lib/pgadmin
    networks:
      - acepanel-network
networks:
  acepanel-network:
    external: true