services:
  openlist:
    image: ${OPENLIST_IMAGE}
    restart: always
    user: "0:0"
    networks:
      - acepanel-network
    ports:
      - "${OPENLIST_PORT_HTTP}:5244"
      - "${OPENLIST_PORT_S3}:5246"
    volumes:
      - ./data:/opt/openlist/data
    environment:
      - TZ=${OPENLIST_TIME_ZONE}
      - UMASK=022
networks:  
  acepanel-network:  
    external: true
