services:
  openlist:
    image: openlistteam/openlist:v4.1.9-aio
    restart: unless-stopped
    user: "0:0"
    networks:
      - acepanel-network
    ports:
      - "${OPENLIST_PORT_HTTP}:5244"
    volumes:
      - ./data:/opt/openlist/data
    environment:
      - OPENLIST_ADMIN_PASSWORD=${OPENLIST_ADMIN_PASSWORD}
      - TZ=${OPENLIST_TIME_ZONE}
      - UMASK=022
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:5244 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  acepanel-network:
    external: true
