services:
  openlist:
    image: openlistteam/openlist:v4.1.9-aio
    restart: unless-stopped
    user: "0:0"
    networks:
      - acepanel-network
    ports:
      - "${OPENLIST_PORT_HTTP}:5244"
    volumes:
      - ./data:/opt/openlist/data
    environment:
      - OPENLIST_ADMIN_PASSWORD=${OPENLIST_ADMIN_PASSWORD}
      - TZ=${OPENLIST_TIME_ZONE}
      - UMASK=022
networks:  
  acepanel-network:  
    external: true
