services:
  dashboard:
    image: ghcr.io/nezhahq/nezha:v2.0.4
    restart: unless-stopped
    networks:
      - acepanel-network
    ports:
      - ${NEZHA_PORT_HTTP}:8008
    volumes:
      - ./data:/dashboard/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:8008 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  acepanel-network:
    external: true
